### ISSUE TITLE
Dataset's license

### ISSUE THREAD

**Issue by mszulc913** [doc-analysis/ReadingBank#4]
Hey!
First of all, thank you for your amazing work! I have a question regarding the license. In the README file I can read: `Our data can only be used for research purpose. Please DO NOT re-distribute our data.` and few lines later it states that `All the data in our dataset will be protected by Apache 2.0 license.` Can we (as a company) use your dataset for commercial purpose (i.e. retrain our own model on it)?

**Comment by mszulc913** [comment]
@HYPJUDY

**Comment by HYPJUDY** [comment]
Hi, thanks for your question. I don't think ReadingBank can be used for commercial purpose since ``Our data can only be used for research purpose.``. Please contact @wolfshow (lecu@microsoft.com) regarding your concern.

**Comment by mszulc913** [comment]
Ok, I see. Thank you for your answer!

**Comment by wolfshow** [comment]
@mszulc913, currently, the dataset can only be used for research purposes.

**Comment by mszulc913** [comment]
ok, thank you for the answer!
